# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: Start all development servers concurrently
    cmds:
      - task: dev

  init:
    desc: Interactive setup - configure and initialize the project
    cmds:
      - python scripts/init.py

  dev:
    desc: Run all development servers (API, web, admin) with color-coded output
    cmds:
      - python scripts/dev.py

  install:
    desc: Install all dependencies using npm workspaces
    cmds:
      - npm install

  build:
    desc: Build all projects (API and frontend workspaces)
    cmds:
      - cargo build --release --manifest-path backend/api/Cargo.toml
      - npm run build

  test:
    desc: Run tests
    cmds:
      - cargo test
      - npm run test